<?php

use Drupal\analytics\AnalyticsService\AnalyticsServiceInterface;

/**
 * Implements hook_theme().
 */
function analytics_theme() {
  $info['analytics_js'] = array(
    'variables' => array('js' => NULL),
    'file' => 'analytics.theme.inc',
  );

  return $info;
}

/**
 * Implements hook_page_bottom().
 */
function analytics_page_bottom(array &$page_bottom) {
  $added = FALSE;
  if (!\Drupal::config('analytics.settings')->get('analytics_disable_page_build')) {
    $manager = \Drupal::service('plugin.manager.analytics.service');
    $plugins = $manager->getDefinitions();
    foreach ($plugins as $analytics_service) {
      /** @var AnalyticsServiceInterface $service_instance */
      $service_instance = $manager->createInstance($analytics_service['id']);
      // Only display AMP tags on AMP pages.
      if (\Drupal::moduleHandler()->moduleExists('amp') && \Drupal::service('router.amp_context')->isAmpRoute()) {
        $plugin_id = $service_instance->getPluginId();
        if ($plugin_id == 'amp_analytics' || $plugin_id == 'amp_tracking_pixel') {
          if ($service_instance->canTrack() && $output = $service_instance->getOutput()) {
            $page_bottom += $output;
            $added = TRUE;
          }
        }
      }
      else {
        if ($service_instance->canTrack() && $output = $service_instance->getOutput()) {
          $page_bottom += $output;
          $added = TRUE;
        }
      }
    }
  }

  if (empty($privacy_dnt = \Drupal::config('analytics.settings')->get('analytics_privacy_dnt'))) {
    $privacy_dnt = TRUE;
  }
  if ($added && $privacy_dnt) {
    $page['page_bottom']['#attached']['library'][] = 'analytics/analytics.dnt';
  }
}
