display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      fields:
        feeds_feed_bulk_form:
          label: 'Mise à jour en masse'
        title:
          label: Titre
        type:
          label: Type
        name:
          label: Nom
        changed:
          label: 'Mis à jour'
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        type:
          expose:
            label: Type
      use_more_text: plus
  page_1:
    display_title: Page
