analytics_privacy_dnt: true
analytics_privacy_anonymize_ip: false
analytics_cache_urls: false
analytics_disable_page_build: false
_core:
  default_config_hash: YZ4gOmSdoLrHZ_o4yR7TJU2gM4EQ_pLpRfPjypehO2k
