minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
jquery_selector: select
search_contains: false
disable_search: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  bartik: '0'
  seven: '0'
  bootstrap: '0'
  drupal8_zymphonies_theme: '0'
chosen_include: 1
_core:
  default_config_hash: 8OBgqA1x01J7SgSvBzOELfxP9Bu998XgnQjf4EN40mo
