module:
  address: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  analytics: 0
  analytics_google: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  editor: 0
  email_form: 0
  entity: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  geolocation_demo: 0
  hal: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_effects: 0
  kint: 0
  language: 0
  link: 0
  liste: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_mobile: 0
  multiple_registration: 0
  node: 0
  options: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  responsive_slideshow: 0
  rest: 0
  reusable_forms: 0
  search_api: 0
  search_api_db: 0
  search_api_views_taxonomy: 0
  search_save: 0
  serialization: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_extender: 0
  update: 0
  user: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webprofiler: 0
  menu_link_content: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  jethro: 0
  drupal8_zymphonies_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
