socialicon_count: '5'
slideshow_count: '3'
slideshow_display: 1
_core:
  default_config_hash: xagp8nuL4woImlRj8AcE_BMnSbVz3o9yH5zcF9Q8iYU
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://logo1_0.png'
favicon:
  use_default: 1
social_class_1: ''
social_url_1: ''
social_class_2: ''
social_url_2: ''
social_class_3: ''
social_url_3: ''
social_class_4: ''
social_url_4: ''
social_class_5: ''
social_url_5: ''
slide_description_1: ''
slide_image_1:
  - '177'
slide_url_1: /poeiminisite/recherche-offre
slide_description_2: ''
slide_image_2:
  - '181'
slide_url_2: /poeiminisite/recherche-offre
slide_description_3: ''
slide_image_3:
  - '182'
slide_url_3: /poeiminisite/recherche-offre
slide_description_4: ''
slide_image_4: {  }
slide_url_4: ''
slide_description_5: ''
slide_image_5: {  }
slide_url_5: ''
slideshow_visiblity: '<front>'
