<?php

/**
 * @file
 * Contains liste.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function liste_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the liste module.
    case 'help.page.liste':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function liste_theme() {
  return [
    'liste' => [
      'template' => 'liste',
      'render element' => 'children',
    ],
  ];
}
