analytics.settings:
  type: mapping
  label: Settings
  mapping:
    analytics_privacy_dnt:
      type: boolean
    analytics_privacy_anonymize_ip:
      type: boolean
    analytics_cache_urls:
      type: boolean
    analytics_disable_page_build:
      type: boolean

analytics.analytics_instance.*:
  type: config_entity
  label: 'Analytics Instance'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    type_id:
      type: string
      label: 'Analytics service plugin ID'
    type_settings:
      type: analytics.analytics_service_settings.[%parent.type_id]

analytics.analytics_service_settings.*:
  type: mapping
  label: 'Analytics service settings'
